on:
  #push:
  #  branches: main
  workflow_dispatch:

name: test

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
 
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::gh
            any::dplyr
            any::tidyr
            any::readr
            any::knitr
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Execute Script
        run: |
          Rscript "scripts/test.R"
      - name: Build page
        run: |
          quarto render docs/test.qmd
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"-

